default:
    image: swipl:stable

stages:
  - build
  - test

before_script:
  - swipl --version
  - ls -l

build-job:
  stage: build
  before_script:
    - apt-get update
    - apt-get install make
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - make
  artifacts:
    paths:
      - lambda_calculus

test-app:
  stage: test
  script:
    - test $(echo "(lx.x) a" | ./lambda_calculus) == $(echo "a" | ./lambda_calculus)
    - test $(echo "(lx.xx) a" | ./lambda_calculus) == $(echo "aa" | ./lambda_calculus)
    - test $(echo "lx.(lx.x)x" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "la.(lx.xx)a" | ./lambda_calculus) == $(echo "lx.xx" | ./lambda_calculus)
    - test $(echo "lx.(lx.xx)x" | ./lambda_calculus) == $(echo "lx.xx" | ./lambda_calculus)
    - test $(echo "lx.(lx.(lx.xx)xx)x" | ./lambda_calculus) == $(echo "lx.xxx" | ./lambda_calculus)

test-nat:
  stage: test
  script:
    - test $(echo "0N" | ./lambda_calculus) == $(echo "(0N)" | ./lambda_calculus)
    - test $(echo "1N" | ./lambda_calculus) == $(echo "(1N)" | ./lambda_calculus)
    - test $(echo "2N" | ./lambda_calculus) == $(echo "(2N)" | ./lambda_calculus)
    - test $(echo "3N" | ./lambda_calculus) == $(echo "(3N)" | ./lambda_calculus)
    - test $(echo "4N" | ./lambda_calculus) == $(echo "(4N)" | ./lambda_calculus)

test-nat_succ:
  stage: test
  needs: [test-nat]
  script:
    - test $(echo "(lnfx.f(nfx))0N" | ./lambda_calculus) == $(echo "(1N)" | ./lambda_calculus)
    - test $(echo "(lnfx.nf(fx))0N" | ./lambda_calculus) == $(echo "(1N)" | ./lambda_calculus)
    - test $(echo "(lnfx.f(nfx))1N" | ./lambda_calculus) == $(echo "(2N)" | ./lambda_calculus)
    - test $(echo "(lnfx.nf(fx))1N" | ./lambda_calculus) == $(echo "(2N)" | ./lambda_calculus)
    - test $(echo "(lnfx.f(nfx))2N" | ./lambda_calculus) == $(echo "(3N)" | ./lambda_calculus)
    - test $(echo "(lnfx.nf(fx))2N" | ./lambda_calculus) == $(echo "(3N)" | ./lambda_calculus)
    - test $(echo "(lnfx.f(nfx))3N" | ./lambda_calculus) == $(echo "(4N)" | ./lambda_calculus)
    - test $(echo "(lnfx.nf(fx))3N" | ./lambda_calculus) == $(echo "(4N)" | ./lambda_calculus)
    - test $(echo "(lnfx.f(nfx))10N" | ./lambda_calculus) == $(echo "(11N)" | ./lambda_calculus)
    - test $(echo "(lnfx.nf(fx))10N" | ./lambda_calculus) == $(echo "(11N)" | ./lambda_calculus)
    - test $(echo "(lnfx.f(nfx))100N" | ./lambda_calculus) == $(echo "(101N)" | ./lambda_calculus)
    - test $(echo "(lnfx.nf(fx))100N" | ./lambda_calculus) == $(echo "(101N)" | ./lambda_calculus)

test-nat_add:
  stage: test
  needs: [test-add]
  script:
    - test $(echo "(lnmfx.nf(mfx)) 12N 13N" | ./lambda_calculus) == $(echo "25N" | ./lambda_calculus)
    - test $(echo "(lnmfx.nf(mfx)) 10N 15N" | ./lambda_calculus) == $(echo "25N" | ./lambda_calculus)
    - test $(echo "(lnmfx.nf(mfx)) 16N 89N" | ./lambda_calculus) == $(echo "105N" | ./lambda_calculus)
    - test $(echo "(lnmfx.nf(mfx)) 0N 5N" | ./lambda_calculus) == $(echo "5N" | ./lambda_calculus)
    - test $(echo "(lnmfx.nf(mfx)) 5N 0N" | ./lambda_calculus) == $(echo "5N" | ./lambda_calculus)
    - test $(echo "(lnmfx.nf(mfx)) 0N 0N" | ./lambda_calculus) == $(echo "0N" | ./lambda_calculus)

test-zal:
  stage: test
  script:
    - test $(echo "-2Z" | ./lambda_calculus) == $(echo "(-2Z)" | ./lambda_calculus)
    - test $(echo "-1Z" | ./lambda_calculus) == $(echo "(-1Z)" | ./lambda_calculus)
    - test $(echo "0Z" | ./lambda_calculus) == $(echo "(0Z)" | ./lambda_calculus)
    - test $(echo "1Z" | ./lambda_calculus) == $(echo "(1Z)" | ./lambda_calculus)
    - test $(echo "2Z" | ./lambda_calculus) == $(echo "(2Z)" | ./lambda_calculus)

test-id:
  stage: test
  script:
    - test $(echo "lx.x" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "la.a" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "\\x.x" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "\\a.a" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "λx.x" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "λa.a" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)

test-id2:
  stage: test
  needs: [test-id]
  script:
    - test $(echo "<>" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "<><>" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "<><><>" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "<><><><>" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
    - test $(echo "<><><><>" | ./lambda_calculus) == $(echo "<>" | ./lambda_calculus)
